### ISSUE TITLE
https://sci-hub.cc/ link

### ISSUE THREAD

**Issue by bibbca** [learn-anything/websites#7]
The link [https://sci-hub.cc/](https://sci-hub.cc/) may be a wrong link.  A quick websearch leads me to this link that may be the correct one: [https://scihub.org/](https://scihub.org/)

**Comment by nikitavoloboev** [comment]
Yep, you are right. Shall I change it or you do? Reviewing #6 now.

**Comment by bibbca** [comment]
Either way, doesn't matter to me. I won't to be able to look at it tomorrow.

**Comment by nikitavoloboev** [comment]
> By the way, thanks for having a great project that I can contribute to and learn more about GitHub!

No problem. 🙂 

Yeah, just make the change in your PR. There are some conflicts there so I can't merge them. But no rush.
